-- 코드를 작성해주세요

SELECT CD.ITEM_ID, CD.ITEM_NAME, CD.RARITY FROM ITEM_INFO AS CD JOIN ITEM_TREE AS IT ON CD.ITEM_ID = IT.ITEM_ID JOIN ITEM_INFO AS PR ON IT.PARENT_ITEM_ID = PR.ITEM_ID WHERE PR.RARITY = 'RARE' ORDER BY CD.ITEM_ID DESC