-- 코드를 작성해주세요

SELECT CH.ID, CH.GENOTYPE, PR.GENOTYPE AS PARENT_GENOTYPE from ECOLI_DATA AS CH JOIN ECOLI_DATA AS PR ON CH.PARENT_ID = PR.ID WHERE (CH.GENOTYPE & PR.GENOTYPE) = PR.GENOTYPE ORDER BY CH.ID